---
title: "Lab 06 - Conveying the right message through visualisation"
author: [team 1_2]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(lubridate)
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~mask_count, ~nomask_count,
  "7/12/2020", 25.4, 9.9,
  "7/13/2020", 19.6, 9.1,
  "7/14/2020", 19.5, 9.3,
  "7/15/2020", 20.5, 9.8,
  "7/16/2020", 19.8, 9.9,
  "7/17/2020", 19.7, 9.5,
  "7/18/2020", 20.5, 9.5,
  "7/19/2020", 19.8, 9.0,
  "7/20/2020", 20.5, 8.5,
  "7/21/2020", 21.5, 8.5,
  "7/22/2020", 19.8, 8.7,
  "7/23/2020", 19.8, 8.5,
  "7/24/2020", 20.5, 9.9,
  "7/25/2020", 19.0, 9.9,
  "7/26/2020", 19.6, 10.1,
  "7/27/2020", 17.0, 9.5, 
  "7/28/2020", 16.1, 9.5,
  "7/29/2020", 16.4, 9.6,
  "7/30/2020", 16.5, 10.0,
  "7/31/2020", 16.0, 8.9,
  "8/1/2020", 16.1, 9.1,
  "8/2/2020", 15.8, 8.9,
  "8/3/2020", 15.9, 9.1)

```


### Exercise 2

```{r better-viz}
pivot_longer(df, c("mask_count", "nomask_count"),
             names_to = "mask_status",
             values_to = "count") %>%
  mutate(date <- mdy(date)) %>%
  ggplot(mapping = aes(x = date, y = count, color = mask_status, group = mask_status)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90))
```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
